# Generated by Django 3.2.8 on 2022-01-30 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landman', '0002_auto_20210705_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreementtype',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agreement_types', to='landman.subjecttype'),
        ),
    ]
