# Generated by Django 3.2.5 on 2021-07-05 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landman', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address_line2',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='address',
            name='attention_line1',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='address',
            name='attention_line2',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
